#!/usr/bin/python

import struct
import sys


def intize(f):
  return struct.unpack(">i", f.read(4))[0] # Big Endian Decode

def reverse_renumberer(filename):
  renumber = {}
  with open(filename, 'rb') as f:
    size = intize(f)
    for i in range(size):
      renumber[i] = intize(f)
    index = intize(f)
  return renumber

if len(sys.argv) < 2:
  print """Produces the id to index mapping, given a list of ids
    from STDIN and the path to the mapping as an argument"""
  print "Example: cat list_of_ids.txt | map_ids_forward path/to/step2xr2.txt"
else:
  renumber = reverse_renumberer(sys.argv[1])
  for l in sys.stdin:
    print renumber[int(l)]
